/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_Func */

#ifndef _Included_JNI_Func
#define _Included_JNI_Func
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_Func
 * Method:    calculate
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_JNI_1Func_calculate
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
