/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CudaJNI */

#ifndef _Included_CudaJNI
#define _Included_CudaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CudaJNI
 * Method:    printHelloWorldByGPU
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CudaJNI_printHelloWorldByGPU
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
