/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    call
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNI_call
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
